ExpenseCategory.find_or_create_by! name: "Spare parts"
ExpenseCategory.find_or_create_by! name: "Driver Salary"
ExpenseCategory.find_or_create_by! name: "TurnBoy Salary"
ExpenseCategory.find_or_create_by! name: "Diesel"
ExpenseCategory.find_or_create_by! name: "Other"
ExpenseCategory.find_or_create_by! name: "Mileage"
ExpenseCategory.find_or_create_by! name: "Staff Salary"